title: zach taiji # name of the site
author: Zach Taiji # name of site's author
email: zach@azntaiji.com # email of site's author
#url: https://riggraz.dev # root address of the site
baseurl: ""

permalink: /:slug.html

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Where things are
source              : .
#destination         : ./_site
collections:
  posts:
    output          : true

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Outputting
#paginate_path       : /page:num
timezone            : America/Los_Angeles

quiet               : false
verbose             : false
defaults            : []

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false