# Where things are
source              : .
#destination         : ./_site
baseurl: ""
sass:
  style: compressed
collections_dir: .
collections:
  graphic-design:
    output: true
    # permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: "graphic_design"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Outputting
permalink: /:slug.html
#paginate_path       : /page:num
timezone            : America/Los_Angeles

quiet               : false
verbose             : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false